build_task:
  container:
    image: python:3.7.2
  prep_script: python3 -m pip install --upgrade setuptools wheel
  script: python3 setup.py sdist bdist_wheel
  setuptools_artifacts:
    path: dist/**
