language: python
os:
  - linux
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - "python3 -m pip install --upgrade setuptools wheel"
script:
  - "python3 setup.py sdist bdist_wheel"
